export default {
  login: 'Fuglydami',
  id: 66129867,
  node_id: 'MDQ6VXNlcjY2MTI5ODY3',
  avatar_url: 'https://avatars.githubusercontent.com/u/66129867?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Fuglydami',
  html_url: 'https://github.com/Fuglydami',
  followers_url: 'https://api.github.com/users/Fuglydami/followers',
  following_url:
    'https://api.github.com/users/Fuglydami/following{/other_user}',
  gists_url: 'https://api.github.com/users/Fuglydami/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Fuglydami/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Fuglydami/subscriptions',
  organizations_url: 'https://api.github.com/users/Fuglydami/orgs',
  repos_url: 'https://api.github.com/users/Fuglydami/repos',
  events_url: 'https://api.github.com/users/Fuglydami/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Fuglydami/received_events',
  type: 'User',
  site_admin: false,
  name: 'Damilare Oyedeji',
  company: null,
  blog: 'fuglydami.github.io',
  location: 'Lagos, Nigeria',
  email: null,
  hireable: null,
  bio: 'Front-End Developer || Javascript || React Js',
  twitter_username: 'blackkolanut',
  public_repos: 35,
  public_gists: 0,
  followers: 7,
  following: 9,
  created_at: '2020-05-29T15:08:15Z',
  updated_at: '2021-01-28T22:36:08Z',
}
