export default [
  {
    login: 'sime0n',
    id: 92902,
    node_id: 'MDQ6VXNlcjkyOTAy',
    avatar_url: 'https://avatars.githubusercontent.com/u/92902?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sime0n',
    html_url: 'https://github.com/sime0n',
    followers_url: 'https://api.github.com/users/sime0n/followers',
    following_url: 'https://api.github.com/users/sime0n/following{/other_user}',
    gists_url: 'https://api.github.com/users/sime0n/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/sime0n/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sime0n/subscriptions',
    organizations_url: 'https://api.github.com/users/sime0n/orgs',
    repos_url: 'https://api.github.com/users/sime0n/repos',
    events_url: 'https://api.github.com/users/sime0n/events{/privacy}',
    received_events_url: 'https://api.github.com/users/sime0n/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'olajvde',
    id: 68570900,
    node_id: 'MDQ6VXNlcjY4NTcwOTAw',
    avatar_url: 'https://avatars.githubusercontent.com/u/68570900?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/olajvde',
    html_url: 'https://github.com/olajvde',
    followers_url: 'https://api.github.com/users/olajvde/followers',
    following_url:
      'https://api.github.com/users/olajvde/following{/other_user}',
    gists_url: 'https://api.github.com/users/olajvde/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/olajvde/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/olajvde/subscriptions',
    organizations_url: 'https://api.github.com/users/olajvde/orgs',
    repos_url: 'https://api.github.com/users/olajvde/repos',
    events_url: 'https://api.github.com/users/olajvde/events{/privacy}',
    received_events_url: 'https://api.github.com/users/olajvde/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'R4M5E5',
    id: 58643307,
    node_id: 'MDQ6VXNlcjU4NjQzMzA3',
    avatar_url: 'https://avatars.githubusercontent.com/u/58643307?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/R4M5E5',
    html_url: 'https://github.com/R4M5E5',
    followers_url: 'https://api.github.com/users/R4M5E5/followers',
    following_url: 'https://api.github.com/users/R4M5E5/following{/other_user}',
    gists_url: 'https://api.github.com/users/R4M5E5/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/R4M5E5/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/R4M5E5/subscriptions',
    organizations_url: 'https://api.github.com/users/R4M5E5/orgs',
    repos_url: 'https://api.github.com/users/R4M5E5/repos',
    events_url: 'https://api.github.com/users/R4M5E5/events{/privacy}',
    received_events_url: 'https://api.github.com/users/R4M5E5/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jeremievalili',
    id: 56654756,
    node_id: 'MDQ6VXNlcjU2NjU0NzU2',
    avatar_url: 'https://avatars.githubusercontent.com/u/56654756?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jeremievalili',
    html_url: 'https://github.com/jeremievalili',
    followers_url: 'https://api.github.com/users/jeremievalili/followers',
    following_url:
      'https://api.github.com/users/jeremievalili/following{/other_user}',
    gists_url: 'https://api.github.com/users/jeremievalili/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jeremievalili/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/jeremievalili/subscriptions',
    organizations_url: 'https://api.github.com/users/jeremievalili/orgs',
    repos_url: 'https://api.github.com/users/jeremievalili/repos',
    events_url: 'https://api.github.com/users/jeremievalili/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jeremievalili/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'okanrence',
    id: 8008109,
    node_id: 'MDQ6VXNlcjgwMDgxMDk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8008109?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/okanrence',
    html_url: 'https://github.com/okanrence',
    followers_url: 'https://api.github.com/users/okanrence/followers',
    following_url:
      'https://api.github.com/users/okanrence/following{/other_user}',
    gists_url: 'https://api.github.com/users/okanrence/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/okanrence/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/okanrence/subscriptions',
    organizations_url: 'https://api.github.com/users/okanrence/orgs',
    repos_url: 'https://api.github.com/users/okanrence/repos',
    events_url: 'https://api.github.com/users/okanrence/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/okanrence/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Adecodess',
    id: 66638496,
    node_id: 'MDQ6VXNlcjY2NjM4NDk2',
    avatar_url: 'https://avatars.githubusercontent.com/u/66638496?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Adecodess',
    html_url: 'https://github.com/Adecodess',
    followers_url: 'https://api.github.com/users/Adecodess/followers',
    following_url:
      'https://api.github.com/users/Adecodess/following{/other_user}',
    gists_url: 'https://api.github.com/users/Adecodess/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Adecodess/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Adecodess/subscriptions',
    organizations_url: 'https://api.github.com/users/Adecodess/orgs',
    repos_url: 'https://api.github.com/users/Adecodess/repos',
    events_url: 'https://api.github.com/users/Adecodess/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Adecodess/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'En-Jen',
    id: 62165571,
    node_id: 'MDQ6VXNlcjYyMTY1NTcx',
    avatar_url: 'https://avatars.githubusercontent.com/u/62165571?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/En-Jen',
    html_url: 'https://github.com/En-Jen',
    followers_url: 'https://api.github.com/users/En-Jen/followers',
    following_url: 'https://api.github.com/users/En-Jen/following{/other_user}',
    gists_url: 'https://api.github.com/users/En-Jen/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/En-Jen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/En-Jen/subscriptions',
    organizations_url: 'https://api.github.com/users/En-Jen/orgs',
    repos_url: 'https://api.github.com/users/En-Jen/repos',
    events_url: 'https://api.github.com/users/En-Jen/events{/privacy}',
    received_events_url: 'https://api.github.com/users/En-Jen/received_events',
    type: 'User',
    site_admin: false,
  },
]
